# Generated by Django 4.2.1 on 2023-06-20 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_comments_user_alter_favorites_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="category",
        ),
        migrations.RemoveField(
            model_name="news",
            name="project",
        ),
        migrations.RemoveField(
            model_name="news",
            name="user_pub",
        ),
    ]
