# Generated by Django 4.2.1 on 2023-06-20 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("core", "0016_remove_news_category_remove_news_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=5000)),
                ("date_pub", models.DateField()),
                ("public", models.BooleanField()),
                ("tags", models.JSONField()),
                ("revision_date", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("needs_revision", models.BooleanField()),
                ("needs_approval", models.BooleanField()),
                ("relevance", models.IntegerField()),
                ("accuracy", models.IntegerField()),
                ("update_date", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="News",
                        to="core.category",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="News",
                        to="core.project",
                    ),
                ),
                (
                    "user_pub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="News",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
